### ISSUE TITLE
Is this sysver?

### ISSUE THREAD

**Issue by bwbroersma** [xocolatl/periods#2]
Your great [PGday 2019 presentation](https://www.postgresql.eu/events/fosdem2019/sessions/session/2299/slides/161/Periods%20and%20System-Versioned%20Tables.pdf) mentions `https://github.com/xocolatl/sysver` which now is a `404`. Is this repository the equivalent of `sysver`?

**Comment by xocolatl** [comment]
This is even better than sysver, which is why I renamed it.  I have created a sysver repo that redirects here to avoid future confusion.  Thanks for the heads up!
