### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by bamper197801** [xocolatl/periods#29]
Good afternoon.
Please tell me how to solve the problem of installing the extension.
I compiled the extension from sources and installed it on PostgreSQL 14 version (not the default version). The extension is present in the list of available ones, but during installation an error occurs -

SQL Error [58P01]: ERROR: could not load library "/usr/local/pgsql/lib/periods.so": /usr/local/pgsql/lib/periods.so: undefined symbol: elog_finish
ERROR: could not load library "/usr/local/pgsql/lib/periods.so": /usr/local/pgsql/lib/periods.so: undefined symbol: elog_finish
ERROR: could not load library "/usr/local/pgsql/lib/periods.so": /usr/local/pgsql/lib/periods.so: undefined symbol: elog_finish

**Comment by df7cb** [comment]
Did you make sure to compile against PG14?

likely so:
`make install PG_CONFIG=/usr/local/pgsql/bin/pg_config`
