### ISSUE TITLE
Remove add_period from a table

### ISSUE THREAD

**Issue by MarcoPignati** [xocolatl/periods#32]
Hello,
For the last few years I used this extension on a specific table 

`SELECT periods.add_period ('measurement', 'validity', 'tstart', 'tend');`

Now I would like to go back to the original behavior. Basically I'd like to be able to write everything on the table without checks on tstart and tend values. I cannot figure out how to do it.

I believe I could leverage on a temporary table, but it seems a bit convoluted. Is there a better approach to remove this function?

**Comment by MarcoPignati** [comment]
![image](https://user-images.githubusercontent.com/35630931/203999161-99f5d47d-acba-438a-80bd-fb93bb3146d9.png)

I think I could achieve what I want by removing the check constrain that the periods.add_period added. Is that correct?
In that case I'd do

![image](https://user-images.githubusercontent.com/35630931/203998997-db471562-2ed5-4fcf-a3e8-dc88a5e2fdce.png)
Is this ok for avoiding the add_period to execute?

**Comment by xocolatl** [comment]
Hi!  You should use the `drop_period()` function.
