### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by shaimaa-elsebaie** [xocolatl/periods#36]
I am new to using extensions with PostgreSQL. I tried copying the release folder content into this location: `/usr/local/opt/postgresql@16/share/postgresql@16/extension` but I am getting an error.

`Detail: Could not open extension control file "/usr/local/opt/postgresql@16/share/postgresql@16/extension/periods.control": No such file or directory.
Hint: The extension must first be installed on the system where PostgreSQL is running.`

I tried copying the `periods.control` file into the same location but I am getting:

`ERROR:  extension "periods" has no installation script nor update path for version "1.2" `

Can you please guide on how I can install the extension?

**Comment by df7cb** [comment]
You need to actually compile it, make, make install.

https://www.postgresql.org/docs/current/extend-pgxs.html
