### ISSUE TITLE
How do I install the extension on an AWS PostgreSQL database?

### ISSUE THREAD

**Issue by shaimaa-elsebaie** [xocolatl/periods#37]
I installed the Periods extension locally by downloading the release file, unzipping it, and copying the files to the appropriate folders. 

Now I want o install it on my production database. It's an AWS PostgreSQL database. Can you please provide me with the steps to do so?

**Comment by df7cb** [comment]
You need to actually compile it, `make`, `make install`. 

https://www.postgresql.org/docs/current/extend-pgxs.html

**Comment by shaimaa-elsebaie** [comment]
Why was this closed? As I mentioned in my original post, I have already installed the extension on my local machine by using `make` and `make install`. 
Now I need to install it on my production instance on AWS RDS. How can I do that?

**Comment by df7cb** [comment]
RDS doesn't allow you to install stuff on disk. You can only use the extensions they already provide, check the AWS docs.

**Comment by shaimaa-elsebaie** [comment]
@df7cb Then where does people who use your extension host their production databases? 

I really need to use your extension on our AWS production database. I found someone online suggesting running the sql scripts that the extension runs directly on database without using `CREATE EXTENSION`. Inside the installation folder of periods, I found a script called `periods--1.2.sql`, I tried to run it on my database but it's giving errors. I can also see that their an entire folder named `sql`. Is it possible for you to provide me with instructions and steps on how to run the sql scripts in `periods` so that I can indirectly install the extension? 

One other solution if you can give me instructions on how to turn `periods` into an extension that uses `pg_tle` so that I can run it on AWS RDS. https://www.postgresql.org/about/news/pg_tle-111-released-2708/

**Comment by xocolatl** [comment]
It is not possible to install this extension on AWS.
