### ISSUE TITLE
How to update system versioning after altering a table?

### ISSUE THREAD

**Issue by m4tf3r** [xocolatl/periods#6]
Hello, I would like to know if there is a suggested way to update system versioning of a table after altering it.
E.g. after adding a column to a table with system versioning, how to update the history table, triggers, etc. so that system versioning works also for the new column.

**Comment by m4tf3r** [comment]
I tried adding the new column manually to the history table and versioning seems to work fine.

**Comment by xocolatl** [comment]
Ideally, you wouldn't be allowed to modify the table while system versioning is active.

The way I envision this working is something like this:

```
BEGIN;
SELECT periods.drop_system_versioning('t');
ALTER TABLE t ...;
ALTER TABLE t_history ...;
SELECT periods.add_system_versioning('t');
COMMIT;
```

I will add some more checks and documentation around this.

Thank you for the report!
