### ISSUE TITLE
How to build extension for linux version?

### ISSUE THREAD

**Issue by danrt** [xocolatl/periods#7]
I want to install this extension for postgres running on linux. 
Is there already a package for linux? If not, is it possible to create one?

**Comment by xocolatl** [comment]
Hello, and thank you for your interest in this extension!

There are packages for both .rpm and .deb in the community repositories (https://yum.postgresql.org/ and https://apt.postgresql.org/).

**Comment by danrt** [comment]
Hello and thank you for your reply.

I have already installed ubuntu with postrgresql and was looking how can I install the periods extension. I could not find any packages for it.
Thank you.

**Comment by danrt** [comment]
I think I got it finally.
Here is the package https://packages.debian.org/sid/database/postgresql-11-periods and managed to install it on an ubuntu version.
Thanks a lot.

**Comment by df7cb** [comment]
> Here is the package https://packages.debian.org/sid/database/postgresql-11-periods and managed to install it on an ubuntu version.

Try apt.postgresql.org instead.
