### ISSUE TITLE
Existing rows system_time_start is set to infinity

### ISSUE THREAD

**Issue by danrt** [xocolatl/periods#8]
Hello

I encountered this scenario when there are already data in the tables and when executing `add_system_time_period` the default value for `system_time_start` is set to `infinity`.

Is this the expected behavior or am I doing something wrong?

Thank you

**Comment by xocolatl** [comment]
Hi, thanks for the report!

I cannot reproduce this.  The `system_time_start` column is set to `-infinity` on pre-existing rows.

If that's what you meant to type, then that is a design choice.  Would you rather it be set to the transaction time that added the column?  I like `-infinity` better but I could make an option I suppose.

**Comment by danrt** [comment]
I was expecting it be set to the transaction time, but it is by design to be set to `-infinity` then I think it is  no issue.
